apiVersion: v1
kind: Pod
metadata:
  name: webapps
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: shadabsk/node-todo-cicd:latest
      ports:
        - containerPort: 8000
